# Generated by Django 4.0.5 on 2022-06-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BotonPagos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagoweb',
            old_name='appId',
            new_name='appid',
        ),
        migrations.RenameField(
            model_name='pagoweb',
            old_name='storeId',
            new_name='storeid',
        ),
    ]
