# Generated by Django 4.0.5 on 2022-06-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_smtp', models.CharField(max_length=60)),
                ('puerto', models.IntegerField(default=587)),
            ],
        ),
    ]
