# Generated by Django 4.0.4 on 2022-05-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='configuracion')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='NODUSNET', help_text='Texto de maximo 30 caracteres', max_length=30)),
                ('titulo2', models.CharField(default='La velocidad que usted necesita', help_text='Texto de maximo 100 caracteres', max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='sliders')),
            ],
        ),
    ]
