# Generated by Django 4.0.4 on 2022-05-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='titulo',
        ),
        migrations.AddField(
            model_name='slider',
            name='color',
            field=models.CharField(blank=True, help_text='En formato hexadecimal', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='titulo1',
            field=models.CharField(blank=True, default='La velocidad que usted necesita', help_text='Texto de maximo 50 caracteres', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='titulo3',
            field=models.CharField(blank=True, default='NODUSNET', help_text='Texto de maximo 100 caracteres', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='titulo2',
            field=models.CharField(blank=True, default='NODUSNET', help_text='Texto de maximo 30 caracteres', max_length=30, null=True),
        ),
    ]
