# Generated by Django 4.0.4 on 2022-05-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_remove_slider_titulo_slider_color_slider_titulo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
