# Generated by Django 4.0.4 on 2022-05-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_configuracion_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
    ]
