# Generated by Django 4.0.4 on 2022-05-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0004_configuracion_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='mision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
