# Generated by Django 4.0.4 on 2022-05-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0005_configuracion_mision_configuracion_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='numero_clientes',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='numero_corporativos',
            field=models.IntegerField(default=145),
        ),
    ]
