# Generated by Django 4.0.4 on 2022-05-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0006_configuracion_numero_clientes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosProximos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='eventos')),
                ('nombre_evento', models.CharField(help_text='Agasajo xxx xxx xxx', max_length=30)),
                ('fecha', models.TimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
