# Generated by Django 4.0.4 on 2022-05-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0007_eventosproximos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosproximos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventosproximos',
            name='nombre_evento',
            field=models.CharField(blank=True, help_text='Agasajo xxx xxx xxx', max_length=30, null=True),
        ),
    ]
