# Generated by Django 4.0.4 on 2022-05-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0008_eventosproximos_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosproximos',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
