# Generated by Django 4.0.4 on 2022-05-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0009_alter_eventosproximos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosproximos',
            name='fecha_iso',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventosproximos',
            name='fecha',
            field=models.TimeField(auto_now=True),
        ),
    ]
