# Generated by Django 4.0.4 on 2022-05-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0010_eventosproximos_fecha_iso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracion',
            options={'verbose_name_plural': 'Configuraciones'},
        ),
        migrations.AlterModelOptions(
            name='eventosproximos',
            options={'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Sliders'},
        ),
        migrations.AddField(
            model_name='configuracion',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
