# Generated by Django 4.0.4 on 2022-05-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0011_alter_configuracion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
