# Generated by Django 4.0.4 on 2022-05-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0012_configuracion_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='domingo_horario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='lunes_viernes_horario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='sabado_horario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
