# Generated by Django 4.0.4 on 2022-06-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0013_configuracion_domingo_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosproximos',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
