# Generated by Django 4.0.4 on 2022-06-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0014_eventosproximos_visitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosproximos',
            name='tipo',
            field=models.CharField(choices=[('Recomendaciones', 'Recomendaciones'), ('Evento', 'Evento')], default='Recomendaciones', max_length=60),
        ),
    ]
