# Generated by Django 4.0.4 on 2022-06-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0015_eventosproximos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosproximos',
            name='nombre_evento',
            field=models.CharField(blank=True, help_text='Agasajo xxx xxx xxx', max_length=100, null=True),
        ),
    ]
