# Generated by Django 4.0.4 on 2022-06-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0016_alter_eventosproximos_nombre_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=60)),
                ('tecnologia', models.CharField(max_length=60)),
                ('comparticion', models.CharField(max_length=20)),
                ('precio_sin_impuesto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('precio_con_impuesto', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Planes',
            },
        ),
    ]
