# Generated by Django 4.0.4 on 2022-06-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0017_planes'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='velocidad',
            field=models.CharField(default=' ', max_length=60),
        ),
    ]
