# Generated by Django 4.0.4 on 2022-06-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0018_planes_velocidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
