# Generated by Django 4.0.4 on 2022-06-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0019_planes_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
