# Generated by Django 4.0.5 on 2022-06-11 02:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0022_alter_mi_empresa_contenido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mi_empresa',
            options={'verbose_name_plural': 'A cerca de Nosotros'},
        ),
        migrations.AlterField(
            model_name='eventosproximos',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
