# Generated by Django 4.0.5 on 2022-06-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0023_alter_mi_empresa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosproximos',
            name='resumen',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
