# Generated by Django 4.0.5 on 2022-06-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0024_eventosproximos_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='pago_linea',
            field=models.BooleanField(default=False),
        ),
    ]
