# Generated by Django 4.0.5 on 2022-06-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0025_configuracion_pago_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosproximos',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
