# Generated by Django 4.0.5 on 2022-06-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abonados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='clientes',
            name='apellidos',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombres',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='razon_social',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
