# Generated by Django 4.0.5 on 2022-06-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abonados', '0004_pagos_fecha_pagos_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
