# Generated by Django 4.0.5 on 2022-06-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abonados', '0009_pagos_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='email',
        ),
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
